/**
 * Lista de municipios de España.
 * Incluye las 52 capitales (50 provincias + Ceuta y Melilla) y los
 * municipios más poblados o turísticamente relevantes.
 *
 * La comparación se hace normalizando (minúsculas, sin acentos, sin
 * espacios extras), de modo que 'Madrid', 'MADRID' y 'madrid' cuentan
 * todos como válidos.
 */

export const SPANISH_CITIES: readonly string[] = [
  'Ceuta',
  'Melilla',
  'Sevilla',
  'Málaga',
  'Córdoba',
  'Granada',
  'Almería',
  'Cádiz',
  'Huelva',
  'Jaén',
  'Jerez de la Frontera',
  'Dos Hermanas',
  'Marbella',
  'Algeciras',
  'Fuengirola',
  'Estepona',
  'Benalmádena',
  'Mijas',
  'Torremolinos',
  'Chiclana de la Frontera',
  'El Puerto de Santa María',
  'San Fernando',
  'Sanlúcar de Barrameda',
  'Roquetas de Mar',
  'El Ejido',
  'Vélez-Málaga',
  'Motril',
  'Utrera',
  'Alcalá de Guadaíra',
  'Linares',
  'Écija',
  'Antequera',
  'La Línea de la Concepción',
  'Mairena del Aljarafe',
  'Níjar',
  'Priego de Córdoba',
  'Ronda',
  'Lucena',
  'Puente Genil',
  'Cabra',
  'Montilla',
  'Baena',
  'Úbeda',
  'Andújar',
  'Martos',
  'Alcalá la Real',
  'Loja',
  'Baza',
  'Guadix',
  'Armilla',
  'Maracena',
  'Coín',
  'Alhaurín el Grande',
  'Alhaurín de la Torre',
  'Rincón de la Victoria',
  'Torrox',
  'Nerja',
  'Benahavís',
  'Manilva',
  'Arcos de la Frontera',
  'Rota',
  'Conil de la Frontera',
  'Los Barrios',
  'Tarifa',
  'Vejer de la Frontera',
  'Ayamonte',
  'Isla Cristina',
  'Lepe',
  'Moguer',
  'Punta Umbría',
  'Aracena',
  'La Carolina',
  'Bailén',
  'Mengíbar',
  'Jódar',
  'Villanueva del Arzobispo',
  'Cazorla',
  'La Carlota',
  'Pozoblanco',
  'Palma del Río',
  'Montoro',
  'Adra',
  'Vícar',
  'Berja',
  'Huércal-Overa',
  'Cuevas del Almanzora',
  'Mojácar',
  'Garrucha',
  'Carboneras',
  'Zaragoza',
  'Huesca',
  'Teruel',
  'Calatayud',
  'Utebo',
  'Ejea de los Caballeros',
  'Jaca',
  'Monzón',
  'Barbastro',
  'Fraga',
  'Alcañiz',
  'Tarazona',
  'Caspe',
  'La Almunia de Doña Godina',
  'Cuarte de Huerva',
  'Villanueva de Gállego',
  'Binéfar',
  'Sabiñánigo',
  'Oviedo',
  'Gijón',
  'Avilés',
  'Siero',
  'Langreo',
  'Mieres',
  'Castrillón',
  'Villaviciosa',
  'Corvera de Asturias',
  'San Martín del Rey Aurelio',
  'Cangas de Onís',
  'Llanes',
  'Ribadesella',
  'Cudillero',
  'Luarca',
  'Tineo',
  'Cangas del Narcea',
  'Navia',
  'Palma',
  'Calvià',
  'Ibiza',
  'Manacor',
  'Marratxí',
  'Llucmajor',
  'Inca',
  'Santa Eulària des Riu',
  'Sant Antoni de Portmany',
  'Alcúdia',
  'Pollença',
  'Santanyí',
  'Felanitx',
  'Andratx',
  'Soller',
  'Sa Pobla',
  'Santa Margalida',
  'Maó',
  'Ciutadella de Menorca',
  'Formentera',
  'Artà',
  'Capdepera',
  'Sant Lluís',
  'Es Mercadal',
  'Es Castell',
  'Alaior',
  'Ferreries',
  'Las Palmas de Gran Canaria',
  'Santa Cruz de Tenerife',
  'San Cristóbal de La Laguna',
  'Telde',
  'Arona',
  'Santa Lucía de Tirajana',
  'Arrecife',
  'San Bartolomé de Tirajana',
  'Adeje',
  'Granadilla de Abona',
  'Los Realejos',
  'La Orotava',
  'Puerto de la Cruz',
  'Candelaria',
  'Güímar',
  'Icod de los Vinos',
  'Ingenio',
  'Agüimes',
  'Mogán',
  'Gáldar',
  'Arucas',
  'Teguise',
  'San Sebastián de la Gomera',
  'Santa Cruz de La Palma',
  'Los Llanos de Aridane',
  'Puerto del Rosario',
  'Pájara',
  'Tuineje',
  'La Oliva',
  'Antigua',
  'Yaiza',
  'Tías',
  'Santander',
  'Torrelavega',
  'Castro-Urdiales',
  'Camargo',
  'Piélagos',
  'El Astillero',
  'Laredo',
  'Santoña',
  'Santa Cruz de Bezana',
  'Reinosa',
  'Suances',
  'Cabezón de la Sal',
  'Los Corrales de Buelna',
  'San Vicente de la Barquera',
  'Comillas',
  'Colindres',
  'Albacete',
  'Toledo',
  'Guadalajara',
  'Ciudad Real',
  'Cuenca',
  'Talavera de la Reina',
  'Puertollano',
  'Hellín',
  'Tomelloso',
  'Alcázar de San Juan',
  'Valdepeñas',
  'Villarrobledo',
  'Almansa',
  'Illescas',
  'Azuqueca de Henares',
  'Seseña',
  'Manzanares',
  'Daimiel',
  'Ocaña',
  'La Roda',
  'Bolaños de Calatrava',
  'Campo de Criptana',
  'Quintanar de la Orden',
  'Socuéllamos',
  'Villacañas',
  'Yeles',
  'Fuensalida',
  'Mota del Cuervo',
  'Almagro',
  'Miguelturra',
  'Valladolid',
  'Burgos',
  'Salamanca',
  'León',
  'Palencia',
  'Zamora',
  'Segovia',
  'Ávila',
  'Soria',
  'Ponferrada',
  'Aranda de Duero',
  'Miranda de Ebro',
  'San Andrés del Rabanedo',
  'Arroyo de la Encomienda',
  'Laguna de Duero',
  'Medina del Campo',
  'Villaquilambre',
  'Benavente',
  'La Bañeza',
  'Astorga',
  'Villablino',
  'Béjar',
  'Ciudad Rodrigo',
  'Guijuelo',
  'Peñaranda de Bracamonte',
  'Santa Marta de Tormes',
  'Villamayor',
  'Cuéllar',
  'El Espinar',
  'San Ildefonso',
  'Arévalo',
  'Las Navas del Marqués',
  'El Tiemblo',
  'Barcelona',
  'L\'Hospitalet de Llobregat',
  'Badalona',
  'Terrassa',
  'Sabadell',
  'Lleida',
  'Tarragona',
  'Mataró',
  'Santa Coloma de Gramenet',
  'Reus',
  'Girona',
  'Cornellà de Llobregat',
  'Sant Boi de Llobregat',
  'Sant Cugat del Vallès',
  'Manresa',
  'Rubí',
  'Vilanova i la Geltrú',
  'Viladecans',
  'Castelldefels',
  'El Prat de Llobregat',
  'Granollers',
  'Cerdanyola del Vallès',
  'Mollet del Vallès',
  'Esplugues de Llobregat',
  'Gavà',
  'Figueres',
  'Sant Adrià de Besòs',
  'Tortosa',
  'Vic',
  'Vilafranca del Penedès',
  'Igualada',
  'Blanes',
  'Lloret de Mar',
  'Salou',
  'Cambrils',
  'El Vendrell',
  'Calafell',
  'Sitges',
  'Sant Feliu de Llobregat',
  'Barberà del Vallès',
  'Olot',
  'Palafrugell',
  'Banyoles',
  'Ripollet',
  'Montcada i Reixac',
  'Martorell',
  'Premià de Mar',
  'Vilassar de Mar',
  'Sant Pere de Ribes',
  'Tossa de Mar',
  'Calella',
  'Pineda de Mar',
  'Malgrat de Mar',
  'Castellar del Vallès',
  'Sant Joan Despí',
  'Sant Andreu de la Barca',
  'Santa Perpètua de Mogoda',
  'Molins de Rei',
  'Ripoll',
  'Puigcerdà',
  'La Seu d\'Urgell',
  'Balaguer',
  'Mollerussa',
  'Tàrrega',
  'Cervera',
  'Valls',
  'Amposta',
  'Gandesa',
  'Torredembarra',
  'Cadaqués',
  'Begur',
  'Sant Feliu de Guíxols',
  'Valencia',
  'Alicante',
  'Elche',
  'Castellón de la Plana',
  'Torrevieja',
  'Orihuela',
  'Gandia',
  'Benidorm',
  'Paterna',
  'Sagunto',
  'Alcoy',
  'Elda',
  'Vila-real',
  'Torrent',
  'Mislata',
  'Alzira',
  'Burjassot',
  'San Vicente del Raspeig',
  'Petrer',
  'Villena',
  'Dénia',
  'Xàtiva',
  'Ontinyent',
  'Manises',
  'La Vall d\'Uixó',
  'Sant Joan d\'Alacant',
  'Xirivella',
  'Catarroja',
  'Aldaia',
  'Paiporta',
  'Alaquàs',
  'Picassent',
  'Almoradí',
  'Crevillente',
  'Novelda',
  'Santa Pola',
  'Altea',
  'Calpe',
  'Jávea',
  'Teulada',
  'Benissa',
  'La Nucía',
  'El Campello',
  'Mutxamel',
  'Villajoyosa',
  'Pilar de la Horadada',
  'Guardamar del Segura',
  'Rojales',
  'San Miguel de Salinas',
  'Oliva',
  'Cullera',
  'Sueca',
  'Alboraya',
  'Tavernes de la Valldigna',
  'Peñíscola',
  'Vinaròs',
  'Benicarló',
  'Burriana',
  'Onda',
  'Almazora',
  'Nules',
  'Requena',
  'Utiel',
  'Buñol',
  'Chiva',
  'Cheste',
  'Bétera',
  'L\'Eliana',
  'Riba-roja de Túria',
  'Quart de Poblet',
  'Silla',
  'Albal',
  'Alfafar',
  'Benetússer',
  'Sedaví',
  'Massamagrell',
  'Massanassa',
  'Rafelbuñol',
  'Puçol',
  'Pobla de Farnals',
  'Meliana',
  'Morella',
  'Badajoz',
  'Cáceres',
  'Mérida',
  'Plasencia',
  'Don Benito',
  'Almendralejo',
  'Villanueva de la Serena',
  'Zafra',
  'Coria',
  'Navalmoral de la Mata',
  'Montijo',
  'Olivenza',
  'Miajadas',
  'Azuaga',
  'Castuera',
  'Jerez de los Caballeros',
  'Trujillo',
  'Arroyo de la Luz',
  'Villafranca de los Barros',
  'Vigo',
  'A Coruña',
  'Ourense',
  'Santiago de Compostela',
  'Lugo',
  'Pontevedra',
  'Ferrol',
  'Narón',
  'Oleiros',
  'Arteixo',
  'Culleredo',
  'Carballo',
  'Ames',
  'Cambre',
  'Ribeira',
  'Redondela',
  'Vilagarcía de Arousa',
  'Cangas',
  'Marín',
  'Sanxenxo',
  'A Estrada',
  'Lalín',
  'Monforte de Lemos',
  'Viveiro',
  'Sarria',
  'Chantada',
  'Verín',
  'O Barco de Valdeorras',
  'Ribadeo',
  'Tui',
  'O Porriño',
  'Nigrán',
  'Baiona',
  'Gondomar',
  'Mos',
  'Salceda de Caselas',
  'Bueu',
  'Moaña',
  'Ponteareas',
  'Mondariz',
  'Soutomaior',
  'Poio',
  'Vilanova de Arousa',
  'A Pobra do Caramiñal',
  'Boiro',
  'Rianxo',
  'Noia',
  'Muros',
  'Carnota',
  'Cee',
  'Corcubión',
  'Fisterra',
  'Muxía',
  'Camariñas',
  'Laxe',
  'Logroño',
  'Calahorra',
  'Arnedo',
  'Haro',
  'Lardero',
  'Alfaro',
  'Nájera',
  'Santo Domingo de la Calzada',
  'Madrid',
  'Móstoles',
  'Alcalá de Henares',
  'Fuenlabrada',
  'Leganés',
  'Getafe',
  'Alcorcón',
  'Torrejón de Ardoz',
  'Parla',
  'Alcobendas',
  'Las Rozas de Madrid',
  'San Sebastián de los Reyes',
  'Pozuelo de Alarcón',
  'Coslada',
  'Rivas-Vaciamadrid',
  'Valdemoro',
  'Majadahonda',
  'Collado Villalba',
  'Aranjuez',
  'Arganda del Rey',
  'Boadilla del Monte',
  'Tres Cantos',
  'Pinto',
  'Colmenar Viejo',
  'San Fernando de Henares',
  'Ciempozuelos',
  'Torrelodones',
  'Villaviciosa de Odón',
  'Galapagar',
  'Mejorada del Campo',
  'Navalcarnero',
  'El Escorial',
  'San Lorenzo de El Escorial',
  'Villanueva de la Cañada',
  'Villanueva del Pardillo',
  'Valdemorillo',
  'Algete',
  'Velilla de San Antonio',
  'Paracuellos de Jarama',
  'Daganzo de Arriba',
  'Humanes de Madrid',
  'Griñón',
  'Navalagamella',
  'Morata de Tajuña',
  'Chinchón',
  'Buitrago del Lozoya',
  'Manzanares el Real',
  'Murcia',
  'Cartagena',
  'Lorca',
  'Molina de Segura',
  'Alcantarilla',
  'Cieza',
  'Yecla',
  'Águilas',
  'San Javier',
  'Jumilla',
  'Totana',
  'Torre-Pacheco',
  'Caravaca de la Cruz',
  'Mula',
  'Mazarrón',
  'Archena',
  'Las Torres de Cotillas',
  'Cehegín',
  'San Pedro del Pinatar',
  'Los Alcázares',
  'Fuente Álamo de Murcia',
  'Abarán',
  'Alhama de Murcia',
  'Santomera',
  'Bullas',
  'Puerto Lumbreras',
  'Calasparra',
  'Pamplona',
  'Tudela',
  'Barañáin',
  'Burlada',
  'Zizur Mayor',
  'Estella-Lizarra',
  'Tafalla',
  'Villava',
  'Ansoáin',
  'Berriozar',
  'Cintruénigo',
  'Sangüesa',
  'Peralta',
  'Alsasua',
  'Huarte',
  'Aoiz',
  'Lodosa',
  'Corella',
  'Olite',
  'Bilbao',
  'Vitoria-Gasteiz',
  'San Sebastián',
  'Baracaldo',
  'Getxo',
  'Irún',
  'Portugalete',
  'Santurtzi',
  'Basauri',
  'Leioa',
  'Errenteria',
  'Eibar',
  'Sestao',
  'Galdakao',
  'Erandio',
  'Hernani',
  'Lasarte-Oria',
  'Amorebieta-Etxano',
  'Arrasate',
  'Tolosa',
  'Bermeo',
  'Durango',
  'Zarautz',
  'Mungia',
  'Sopela',
  'Pasaia',
  'Andoain',
  'Oñati',
  'Azpeitia',
  'Zumárraga',
  'Llodio',
  'Amurrio',
  'Vitoria',
  'Bergara',
  'Azkoitia',
  'Beasain',
  'Ordizia',
  'Hondarribia',
  'Getaria',
  'Laguardia',
  'Frigiliana',
  'Albarracín',
  'Alquézar',
  'Aínsa',
  'Pedraza',
  'Consuegra',
  'Potes',
  'Santillana del Mar',
] as const;

/** Normaliza una cadena para comparación: trim, minúsculas, sin acentos. */
export function normalizeSpanishCity(input: string): string {
  return input
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/\s+/g, ' ')
    .replace(/[\u2018\u2019\u2032`´]/g, "'")
    .trim();
}

const NORMALIZED_SET = new Set(SPANISH_CITIES.map(normalizeSpanishCity));

/** Devuelve true si la ciudad indicada existe en la lista oficial. */
export function isValidSpanishCity(input: string): boolean {
  if (!input || typeof input !== 'string') return false;
  return NORMALIZED_SET.has(normalizeSpanishCity(input));
}
